/******************************************************************************

                          Guess the no.game

*******************************************************************************/
#include<stdio.h>
#include<stdlib.h>
#include<time.h>

int main()
{
    int num1 = 0, num2 = 0, flag=1;
    
    while(flag)            //outer loop for reply
    {
        srand(time(0));
        num1 = 1+ rand()%100;            //generate random no. b/w 1 to 100
    
        //printf("Number generated by computer\n");
        printf("Number generated by computer is: %d\n", num1);

        printf("Guess the number...\n");
    
    
        while(1)            // inner loop to match the number
        {  
            scanf("%d", &num2);
            if(num2 == num1)
                {
                    printf("Great, You got it !!!!..\n");
                    printf("Do you want to play again ?\nEnter 1 for YES else 0 for NO\n");
                    scanf("%d", &flag);
                    break;
            
                }
    
                else if(num1 > num2)
                {
                    printf("Too Low, Try again\n");
                }

                else
                {
                    printf("Too High, Try again\n");        
                }
        } 
            
    }

    printf("Thanks for playing...\n");

    return 0;    
}

